// ─────────────────────────────────────────────────────────────────────────
// GET /api/account/export
//
// Streams a JSON file containing everything the user owns or is a party to:
//   - profile (sanitized: no oauth tokens or sensitive third-party secrets)
//   - all collections (active + archived implicit from records)
//   - all records (excluding pending-delete — those are about to vanish,
//     not part of the user's stable inventory)
//   - all junction rows record_collections (so a future re-import can rebuild
//     the many-to-many structure if needed)
//   - all tracks linked to the user's records
//   - all custom fields linked to the user's records
//   - all friendships the user is party to (either side)
//   - all direct messages the user has sent OR received
//   - blocks the user has made (NOT blocks made against them — see below)
//   - abuse reports the user has FILED (NOT reports filed against them — see below)
//   - a small "people" lookup so message/friendship counterparts show a
//     readable name instead of a bare UUID, where that person's profile is
//     visible to us (private profiles fall back to just the UUID)
//
// Format is documented in DEPLOY_NOTES and stable enough to import elsewhere.
//
// ── Two deliberate exclusions (this is a right-of-access export, not a
//    complete mirror of every row that mentions the user) ──────────────────
//
//   1. Reports FILED AGAINST this user are not included, only reports THIS
//      user filed. Hyllah's reporting system is deliberately anonymous to
//      the reported party (see src/lib/server/blocks.js) so people can flag
//      abuse without fear of retaliation. Exporting "who reported you and
//      why" would undermine that protection for every reporter who has ever
//      flagged this account, which outweighs this account's marginal
//      right-of-access interest in that specific data. If this policy is
//      ever revisited, it needs a product/legal decision, not a silent
//      code change.
//   2. Blocks made AGAINST this user (i.e. who has blocked them) are not
//      included, only blocks this user has made. Being blocked is the other
//      party's own action/preference, not data generated by this account.
//
// Both exclusions are also stated in the exported file's _meta.notes so the
// end user sees them directly, not just in this comment.
//
// Security:
//   - Hard authentication check via safeGetSession
//   - All queries are scoped to user.id — RLS would also enforce, but explicit
//     filtering is defense-in-depth
//   - Sensitive fields stripped: oauth tokens, raw email duplicate
// ─────────────────────────────────────────────────────────────────────────

import { error } from '@sveltejs/kit';

/** Strip fields that should never leave the server even in a user's own export. */
function sanitizeProfile(profile) {
  if (!profile) return null;
  // Be allow-list rather than deny-list: anything we don't explicitly list
  // doesn't make it out, so future columns can't accidentally leak.
  return {
    id: profile.id,
    email: profile.email,
    username: profile.username,
    display_name: profile.display_name,
    bio: profile.bio,
    avatar_url: profile.avatar_url,
    display_currency: profile.display_currency,
    card_back_view: profile.card_back_view,
    use_discogs_prices: profile.use_discogs_prices,
    show_value_source: profile.show_value_source,
    is_public: profile.is_public,
    show_values_publicly: profile.show_values_publicly,
    discogs_username: profile.discogs_username,  // public handle; the secret is the token
    discogs_connected_at: profile.discogs_connected_at,
    tos_accepted_at: profile.tos_accepted_at,
    tos_version: profile.tos_version,
    created_at: profile.created_at,
    updated_at: profile.updated_at
  };
}

/** @type {import('./$types').RequestHandler} */
export const GET = async ({ locals: { safeGetSession, supabase } }) => {
  const { user } = await safeGetSession();
  if (!user) throw error(401, 'Not signed in');

  // Fetch everything in parallel. Explicit user_id/participant filters on
  // each query (defense-in-depth alongside RLS).
  const [
    profileRes, collectionsRes, recordsRes, junctionRes,
    friendshipsRes, messagesRes, blockedRes, reportsFiledRes
  ] = await Promise.all([
    supabase.from('users').select('*').eq('id', user.id).maybeSingle(),
    supabase.from('collections').select('*').eq('user_id', user.id),
    supabase
      .from('records')
      .select('*')
      .eq('user_id', user.id)
      .eq('is_pending_delete', false),
    supabase
      .from('record_collections')
      .select('record_id, collection_id, added_at, records!inner(user_id)')
      .eq('records.user_id', user.id),
    // Friendships this user is party to, either side.
    supabase
      .from('friendships')
      .select('id, requester_id, addressee_id, status, created_at, updated_at')
      .or(`requester_id.eq.${user.id},addressee_id.eq.${user.id}`),
    // Every message sent OR received — a user's own conversation history
    // is their data regardless of which side of it they were on.
    supabase
      .from('messages')
      .select('id, sender_id, receiver_id, body, created_at, read_at, deleted_by_sender, deleted_by_receiver')
      .or(`sender_id.eq.${user.id},receiver_id.eq.${user.id}`)
      .order('created_at', { ascending: true }),
    // Blocks THIS user has made (not blocks made against them — see header note).
    supabase.from('blocks').select('blocked_id, created_at').eq('blocker_id', user.id),
    // Reports THIS user has filed (not reports filed against them — see header note).
    supabase.from('abuse_reports').select('id, reported_id, reason, created_at').eq('reporter_id', user.id)
  ]);

  if (profileRes.error)      throw error(500, profileRes.error.message);
  if (collectionsRes.error)  throw error(500, collectionsRes.error.message);
  if (recordsRes.error)      throw error(500, recordsRes.error.message);
  if (junctionRes.error)     throw error(500, junctionRes.error.message);
  if (friendshipsRes.error)  throw error(500, friendshipsRes.error.message);
  if (messagesRes.error)     throw error(500, messagesRes.error.message);
  if (blockedRes.error)      throw error(500, blockedRes.error.message);
  if (reportsFiledRes.error) throw error(500, reportsFiledRes.error.message);

  const recordIds = (recordsRes.data ?? []).map((r) => r.id);

  // Tracks + custom fields for all the user's records, each in one query.
  let tracks = [];
  let customFields = [];
  if (recordIds.length > 0) {
    const [tracksRes, customFieldsRes] = await Promise.all([
      supabase
        .from('tracks')
        .select('*')
        .in('record_id', recordIds)
        .order('record_id', { ascending: true })
        .order('sort_order', { ascending: true }),
      supabase
        .from('custom_fields')
        .select('*')
        .in('record_id', recordIds)
        .order('record_id', { ascending: true })
        .order('sort_order', { ascending: true })
    ]);
    if (tracksRes.error) throw error(500, tracksRes.error.message);
    if (customFieldsRes.error) throw error(500, customFieldsRes.error.message);
    tracks = tracksRes.data ?? [];
    customFields = customFieldsRes.data ?? [];
  }

  // Strip the noise from junction rows — the nested records.user_id join was
  // only for filtering and shouldn't be in the output.
  const junctionRows = (junctionRes.data ?? []).map(({ record_id, collection_id, added_at }) => ({
    record_id, collection_id, added_at
  }));

  const friendships = friendshipsRes.data ?? [];
  const messages = messagesRes.data ?? [];
  const blockedUsers = blockedRes.data ?? [];
  const reportsFiled = reportsFiledRes.data ?? [];

  // Build a small "people" lookup so message/friendship counterparts show a
  // readable username instead of a bare UUID. RLS only lets us see a public
  // profile or our own — a counterpart with a private profile is simply
  // omitted here and stays a UUID in the export, which is expected, not a bug.
  const counterpartIds = new Set();
  for (const m of messages) counterpartIds.add(m.sender_id === user.id ? m.receiver_id : m.sender_id);
  for (const f of friendships) counterpartIds.add(f.requester_id === user.id ? f.addressee_id : f.requester_id);
  for (const b of blockedUsers) counterpartIds.add(b.blocked_id);
  counterpartIds.delete(user.id);

  let people = {};
  if (counterpartIds.size > 0) {
    const { data: peopleData } = await supabase
      .from('users')
      .select('id, username, display_name')
      .in('id', [...counterpartIds]);
    for (const p of peopleData ?? []) {
      people[p.id] = { username: p.username, display_name: p.display_name };
    }
  }

  const exportedAt = new Date().toISOString();

  const payload = {
    _meta: {
      app: 'Hyllah',
      app_url: 'https://hyllah.com',
      schema_version: '2',
      exported_at: exportedAt,
      exported_by: user.id,
      record_count: recordIds.length,
      collection_count: collectionsRes.data?.length ?? 0,
      track_count: tracks.length,
      custom_field_count: customFields.length,
      friendship_count: friendships.length,
      message_count: messages.length,
      notes: [
        'people: a lookup of counterpart user IDs referenced in messages/friendships/blocked_users below, mapped to readable username + display name where that profile is visible to us. A counterpart with a private profile appears only as a UUID.',
        'reports_filed contains reports YOU filed. Reports filed AGAINST you by others are intentionally excluded \u2014 Hyllah\u2019s reporting system is anonymous to the reported party by design, to protect people from retaliation for flagging abuse.',
        'blocked_users contains accounts YOU have blocked. Being blocked by someone else is not included, since that is the other person\u2019s own data, not yours.'
      ]
    },
    profile: sanitizeProfile(profileRes.data),
    collections: collectionsRes.data ?? [],
    records: recordsRes.data ?? [],
    record_collections: junctionRows,
    tracks,
    custom_fields: customFields,
    friendships,
    messages,
    blocked_users: blockedUsers,
    reports_filed: reportsFiled,
    people
  };

  // Build a sensible filename: hyllah-export-2025-05-20.json
  const dateStr = exportedAt.slice(0, 10);
  const filename = `hyllah-export-${dateStr}.json`;

  return new Response(JSON.stringify(payload, null, 2), {
    status: 200,
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
      'Content-Disposition': `attachment; filename="${filename}"`,
      // No caching — this is fresh data, possibly sensitive
      'Cache-Control': 'no-store, max-age=0'
    }
  });
};
